---
server:
  sqs:
    enabled: true
    port: 9997
    host: 0.0.0.0
    keys:
      - accesskey: AKIAIOSFODNN7EXAMPLE
        secretkey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

  dashboard:
    enabled: true
    port: 9998
    host: 0.0.0.0

  sqlite:
    path: /data/smoothmq.sqlite
